name: My First Workflow

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code  #clone a repo
        uses: actions/checkout@v4

      - name: list file
        run: ls -al
      
      - name: setup node
        run: actions/setup-node@v4

      - name: check node version
        run: npm -v